CREATE TABLE `consumption_log` (
	`userId` INTEGER PRIMARY KEY,
	`itemId` INTEGER NOT NULL,
	`amount` INTEGER NOT NULL,
	`cost` INTEGER NOT NULL,
	`timestamp` INTEGER NOT NULL
);
CREATE TABLE `items` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`name` VARCHAR(256) NOT NULL,
	`credits` INTEGER
);
CREATE TABLE `users` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`username` VARCHAR(256) NOT NULL,
	`password` VARCHAR(256) NOT NULL,
	`credits` INTEGER NOT NULL,
	`admin` INTEGER NOT NULL
);