CREATE TABLE `consumption_log` (
	`userID` INTEGER PRIMARY KEY,
	`itemID` INTEGER NOT NULL,
	`amount` INTEGER NOT NULL,
	`cost` INTEGER NOT NULL,
	`timestamp` INTEGER NOT NULL
);
CREATE TABLE `items` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`name` VARCHAR(256) NOT NULL,
	`cost` INTEGER
);
CREATE TABLE `items_stats` (
	`itemID` INTEGER PRIMARY KEY,
	`consumed` INTEGER NOT NULL
);
CREATE TABLE `user_items_stats` (
	`userID` INTEGER PRIMARY KEY,
	`itemID` INTEGER NOT NULL,
	`consumed` INTEGER NOT NULL
);
CREATE TABLE `users` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`username` VARCHAR(256) NOT NULL,
	`password` VARCHAR(256) NOT NULL,
	`credits` INTEGER NOT NULL,
	`admin` INTEGER NOT NULL
);