class FormIDs:
    ITEM_MENU_FRM = 'ITEM_MENU_FRM'
    ITEM_CREATE_FRM = 'ITEM_CRT_FRM'
    ITEM_EDIT_FRM = 'ITEM_EDIT_FRM'
    ITEM_LIST_FRM = 'ITEM_LIST_FRM'

    USER_MENU_FRM = 'USER_MENU_FRM'
    USER_CHANGE_PASSWORD_FRM = 'USER_CHANGE_PASSWORD_FRM'
    USER_CHANGE_PASSWORD_OTHER_FRM = 'USER_CHANGE_PASSWORD_OTHER_FRM'
    USER_CREATE_FRM = 'USER_CREATE_FRM'
    USER_ENROLL_RFID_FRM = 'USER_ENROLL_RFID_FRM'
    USER_LIST_FRM = 'USER_LIST_FRM'

    CREDITS_MENU_FRM = 'CREDITS_MENU_FRM'
    CREDITS_ADD_FRM = 'CREDITS_ADD_FRM'
    CREDITS_WITHDRAW_FRM = 'CREDITS_WITHDRAW_FRM'
    CREDITS_TRANSFER_FRM = 'CREDITS_TRANSFER_FRM'

