# coding: utf-8

# flake8: noqa
"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.auth_success import AuthSuccess
from swagger_client.models.error import Error
from swagger_client.models.item import Item
from swagger_client.models.item_stats import ItemStats
from swagger_client.models.service_stats import ServiceStats
from swagger_client.models.service_stats_items import ServiceStatsItems
from swagger_client.models.service_stats_items_cost import ServiceStatsItemsCost
from swagger_client.models.service_stats_users import ServiceStatsUsers
from swagger_client.models.service_stats_users_credits import ServiceStatsUsersCredits
from swagger_client.models.transferred_credits import TransferredCredits
from swagger_client.models.user import User
from swagger_client.models.user_stats import UserStats
