# coding: utf-8

# flake8: noqa
"""
    MaaS

    Draft for MaaS (Matomat as a Service)  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.auth_success import AuthSuccess
from swagger_client.models.error import Error
from swagger_client.models.item import Item
from swagger_client.models.item_stats import ItemStats
from swagger_client.models.transferred_credits import TransferredCredits
from swagger_client.models.user import User
from swagger_client.models.user_stats import UserStats
