# coding: utf-8

"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.user import User  # noqa: F401,E501


class TransferredCredits(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sender': 'User',
        'credits': 'int'
    }

    attribute_map = {
        'sender': 'sender',
        'credits': 'credits'
    }

    def __init__(self, sender=None, credits=None):  # noqa: E501
        """TransferredCredits - a model defined in Swagger"""  # noqa: E501

        self._sender = None
        self._credits = None
        self.discriminator = None

        if sender is not None:
            self.sender = sender
        if credits is not None:
            self.credits = credits

    @property
    def sender(self):
        """Gets the sender of this TransferredCredits.  # noqa: E501


        :return: The sender of this TransferredCredits.  # noqa: E501
        :rtype: User
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this TransferredCredits.


        :param sender: The sender of this TransferredCredits.  # noqa: E501
        :type: User
        """

        self._sender = sender

    @property
    def credits(self):
        """Gets the credits of this TransferredCredits.  # noqa: E501


        :return: The credits of this TransferredCredits.  # noqa: E501
        :rtype: int
        """
        return self._credits

    @credits.setter
    def credits(self, credits):
        """Sets the credits of this TransferredCredits.


        :param credits: The credits of this TransferredCredits.  # noqa: E501
        :type: int
        """

        self._credits = credits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferredCredits):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
